name: Node.js CI

on:
  workflow_call:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: prosegrinder/.github/.github/workflows/npm-lint.yaml@main

  test:
    needs: lint
    uses: prosegrinder/.github/.github/workflows/npm-test.yaml@main

  cz-dry-run:
    needs: test
    uses: prosegrinder/.github/.github/workflows/cz-dry-run.yaml@main
